In [6]:
# Bodlogo 1
import numpy as np

massiv = np.arange(30,71,2)

print(massiv)
print(len(massiv))


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
21


In [14]:
# Bodlogo 2

celsus = np.random.randint(-51 ,51,10)
fahrenheit = np.random.randint(-10,10, 10)

convertFahrenheit = lambda celsus: 9/5 * celsus + 32
convertCelsus = lambda farenheit: 5/9 * (farenheit - 32)

print("Celsus: ", celsus)
print("Converted to Fahrenheit", convertFahrenheit(celsus))
print("Fahrenheit ", fahrenheit)
print("Converted to Celsus", np.round(convertCelsus(fahrenheit), 1))


Celsus:  [ 33   1 -22   9 -49  -8   1   1 -24  34]
Converted to Fahrenheit [ 91.4  33.8  -7.6  48.2 -56.2  17.6  33.8  33.8 -11.2  93.2]
Fahrenheit  [  5   3  -1 -10  -8  -2   5  -3   7  -4]
Converted to Celsus [-15.  -16.1 -18.3 -23.3 -22.2 -18.9 -15.  -19.4 -13.9 -20. ]


In [22]:
# Bodlogo 3

x = np.arange(1,7,1)

print("x Matrix:",x)

print("z Matrix:", np.reshape(x,(2,3)))
print("y Matrix:",np.reshape(x,(3,2)))


x Matrix: [1 2 3 4 5 6]
z Matrix: [[1 2 3]
 [4 5 6]]
y Matrix: [[1 2]
 [3 4]
 [5 6]]


In [50]:
# Bodlogo 4

a = np.random.randint(90, 110, 5)
b = np.array(['a', 'e', 'i', 'o', 'u'])

print(a)
print(b)
print(b[a > 100])


[ 94  98 108  95 101]
['a' 'e' 'i' 'o' 'u']
['i' 'u']


In [80]:
# Bodlogo 5

a, b = np.arange(1, 13).reshape(4,3), np.arange(1, 9).reshape(4,2)

print(a)
print(b)

result = a.T.dot(b)
print(result)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[118 140]
 [134 160]
 [150 180]]


In [4]:
# Bodlogo 6
import pandas as pd

x = pd.Series([1,2,3,4,5,6,7,8,9,5,3])

medx = x.mean()
stdx = x.std()
print("Mean: ", medx, "str: ", stdx)



Mean:  4.818181818181818 str:  2.522624895547565


In [5]:
# Bodlogo 7

s = 'php', 'python', 'java', 'c#'
print(s)

for i in s:


('php', 'python', 'java', 'c#')
